TRAIN:
  ENABLE: True
  DATASET: ptvfishbase
  BATCH_SIZE: 1
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 10
  AUTO_RESUME: True
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  PATH_TO_DATA_DIR: '/home/shirbar/Desktop/data/single_fish'

  TRAIN_JITTER_SCALES: [256]
  TRAIN_CROP_SIZE: 256
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [1]
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 8
  NUM_GROUPS: 1
  DEPTH: 18
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[1], [1], [1], [1]]
NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.1 # 1-node
  BASE_LR_SCALE_NUM_SHARDS: True
  LR_POLICY: cosine
  #COSINE_END_LR: 0.0001
  #STEP_SIZE: 10
  MAX_EPOCH: 1000
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 34.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 1
  ARCH: fast
  MODEL_NAME: PTVResNetAutoencoder
  LOSS_FUNC: l1
  DROPOUT_RATE: 0.0
TEST:
  ENABLE: False
  DATASET: ptvfishbase
  BATCH_SIZE: 1
  NUM_SPATIAL_CROPS: 1
  NUM_ENSEMBLE_VIEWS: 1
DATA_LOADER:
  NUM_WORKERS: 1 #8
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: '/mnt/results_to_copy/'
TENSORBOARD:
  ENABLE: True
